### ISSUE TITLE
Use tree-sitter for AST modification

### ISSUE THREAD

**Issue by sandstrom** [calicoday/ruby-tree-sitter-ffi#1]
Perhaps this is a stupid question, but is it possible to use tree-sitter to parse source code, then make modifications on the AST and write it back?

So basically do stuff similar to a codemod (https://github.com/benjamn/recast).

I'm curious if we could use this project to parse Swift code in Ruby, modify it, and then write it back to a string of Swift code.

**Comment by calicoday** [comment]
Well, I very much hope it will be. My own focus thus far has been getting a fairly rich api to tree-sitter going in Ruby and make really exploring/experimenting with such things all the easier. I think the big challenge cross-language will be that you need to understand each particular lang parser's grammar well (not just the lang itself) to relate them -- the naming, even some structuring, is specific to each take. 

Me, I do a lot with Rubymotion and the possibility of processing Swift snippets in Ruby is very attractive. 😁

**Comment by sandstrom** [comment]
Thanks, much appreciated!

I'm doing some planning around a project where we may need to parse Swift (or perhaps some other language) to an AST, do code transformation (e.g. renaming all functions with a certain name) and then write it back to a string of source code.

We'll know more within a few months, so I may get back with more questions.

I think we can close this issue though. There is nothing wrong with ruby-tree-sitter-ffi. I just wanted to ask the question.
